sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"
  - lts/*
  - current
matrix:
  include:
    - node_js: "12"
      env: TEST_SUITE=coverage
    - node_js: "12"
      env: TEST_SUITE=lint
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
